export enum Nivel {
    INFANTIL = 'INFANTIL',
    FUNDAMENTAL_1 = 'FUNDAMENTAL_1',
    FUNDAMENTAL_2 = 'FUNDAMENTAL_2',
    FUNDAMENTAL_1_2 = 'FUNDAMENTAL_1_2',
    INFANTIL_FUNDAMENTAL_1 = 'INFANTIL_FUNDAMENTAL_1',
    INFANTIL_FUNDAMENTAL_1_2 = 'INFANTIL_FUNDAMENTAL_1_2',
  }
  